## Alle Klassen mit Spalten der deklarierten Tabellen
from tables import *

class HDF5_info_spalten(IsDescription):
    ID                          =IntCol(pos=0)
    Name                        =StringCol(100,pos=1)
    Speicherort                 =StringCol(256,pos=2)
    Datum                       =StringCol(10,pos=3)
    Auswertungsalgorithmus      =StringCol(5,pos=4)
    Ergebnis                    =StringCol(10,pos=12)

class HDF5_koerper_daten_spalten(IsDescription):
    ID = IntCol(pos=0)
    Flaecheninhalt_gesamt = Float64Col(pos=1)
    Boxoberflaeche = Float64Col(pos=2)
    Koerper_durch_Box_Flaeche = Float64Col(pos=3)
    Koerper_Volumen= Float64Col(pos=4)
    Box_Volumen= Float64Col(pos=5)
    Koerper_durch_Box_Volumen = Float64Col(pos=6)
    Abstand_Schwerpunkte_Koerper_Box = Float64Col(pos=7)
    Verhaeltnis_Box_LB = Float64Col(pos=8)
    Verhaeltnis_Box_LH = Float64Col(pos=9)
    Verhaeltnis_Box_HB = Float64Col(pos=10)
    Datum = StringCol(10,pos=11)

class HDF5_randbox_spalten(IsDescription):
    ID = IntCol(pos=0)
    Laenge = Float64Col(pos=1)
    Hoehe = Float64Col(pos=2)
    Breite = Float64Col(pos=3)
    Volumen_Bauteil = Float64Col(pos=4)
    Volumen_Box = Float64Col(pos=5)
    Koordinaten_P1_x = Float64Col(pos=6)
    Koordinaten_P1_y = Float64Col(pos=7)
    Koordinaten_P1_z = Float64Col(pos=8)
    Koordinaten_P2_x = Float64Col(pos=9)
    Koordinaten_P2_y = Float64Col(pos=10)              
    Koordinaten_P2_z = Float64Col(pos=11)
    Orientierung_1_x = Float64Col(pos=12)
    Orientierung_1_y = Float64Col(pos=13)
    Orientierung_1_z = Float64Col(pos=14)
    Orientierung_2_x = Float64Col(pos=15)
    Orientierung_2_y = Float64Col(pos=16)
    Orientierung_2_z = Float64Col(pos=17)
    Orientierung_3_x = Float64Col(pos=18)
    Orientierung_3_y = Float64Col(pos=19)
    Orientierung_3_z = Float64Col(pos=20)
    Schwerpunkt_Koerper_x = Float64Col(pos=21)
    Schwerpunkt_Koerper_y = Float64Col(pos=22)
    Schwerpunkt_Koerper_z=Float64Col(pos=23)
    Schwerpunkt_Box_x=Float64Col(pos=24)
    Schwerpunkt_Box_y=Float64Col(pos=25)
    Schwerpunkt_Box_z=Float64Col(pos=26)
    Datum = StringCol(10,pos=27)
    
class HDF5_flaechen_spalten_NX(IsDescription):
    ID = IntCol(pos=0)
    Flaeche = Float64Col(pos=1)
    Tag = IntCol(pos=2)
    NXID = IntCol(pos=3)
    Typ = IntCol(pos=5)
    Punkt_x = Float64Col(pos=6)
    Punkt_y = Float64Col(pos=7)
    Punkt_z = Float64Col(pos=8)
    Dir_x = Float64Col(pos=9)
    Dir_y = Float64Col(pos=10)
    Dir_z = Float64Col(pos=11)
    Radius = Float64Col(pos=12)
    Radius_data = Float64Col(pos=13)
    Norm_Dir = Float64Col(pos=14)
    u = Float64Col(pos=15)
    v = Float64Col(pos=16)
    P_Punkt_x = Float64Col(pos=17)
    P_Punkt_y = Float64Col(pos=18)
    P_Punkt_z = Float64Col(pos=19)
    u_1_x = Float64Col(pos=20)
    u_1_y = Float64Col(pos=21)
    u_1_z = Float64Col(pos=22)
    v_1_x = Float64Col(pos=23)
    v_1_y = Float64Col(pos=24)
    v_1_z = Float64Col(pos=25)
    u_2_x = Float64Col(pos=26)
    u_2_y = Float64Col(pos=27)
    u_2_z = Float64Col(pos=28)
    v_2_x = Float64Col(pos=29)
    v_2_y = Float64Col(pos=30)
    v_2_z = Float64Col(pos=31)
    P_Norm_x = Float64Col(pos=32)
    P_Norm_y = Float64Col(pos=33)
    P_Norm_z = Float64Col(pos=34)
    P_Radius_1 = Float64Col(pos=35)
    P_Radius_2 = Float64Col(pos=36)
    Anzahl_Konvex = IntCol(pos=37)
    Anzahl_Konkav = IntCol(pos=38)
    Anzahl_Eben = IntCol(pos=39)
    Nachbarart = StringCol(20,pos=40)
    Datum = StringCol(10,pos=41)

class HDF5_flaechen_spalten_zusammengefasst(IsDescription):
    ID = IntCol(pos=0)
    Flaecheninhalt = Float64Col(pos=2)
    Anzahl_Konvex = IntCol(pos=3)
    Anzahl_Konkav = IntCol(pos=4)
    Nachbarart = StringCol(20,pos=5)
    Datum = StringCol(10,pos=6)

class HDF5_spalten_verteilungen_kruemmung_koerper(IsDescription):
    ID = IntCol(pos=0)
    ## Kruemmungen
    k_n_25=Float64Col(pos=1)
    k_n_15 = Float64Col(pos=2)
    k_n_10 = Float64Col(pos=3)
    k_n_05 = Float64Col(pos=4)
    k_00 = Float64Col(pos=5)
    k_p_05 = Float64Col(pos=6)
    k_p_10 = Float64Col(pos=7)
    k_p_15 = Float64Col(pos=8)
    k_20 = Float64Col(pos=9)
    k_p_25 = Float64Col(pos=10)
    k_anzahl=IntCol(pos=11)
    Datum = StringCol(10,pos=12)
class HDF5_flaechen_spalten_verteilungen_einordnung_koerper(IsDescription):
    ID = IntCol(pos=0)
    ## einordnung 
    Grundflaechen = Float64Col(pos=1)
    Uebergangsflaechen = Float64Col(pos=2)
    Featureflaechen_konkav = Float64Col(pos=3)
    Featureflaechen_konvex = Float64Col(pos=4)
    e_anzahl=IntCol(pos=5)
    Datum = StringCol(10,pos=6)
class HDF5_flaechen_spalten_verteilungen_nx_typ_koerper(IsDescription):
    ID = IntCol(pos=0)
    ## NX Typ
    nx_16 = Float64Col(pos=1)
    nx_17 = Float64Col(pos=2)
    nx_18 = Float64Col(pos=3)
    nx_19 = Float64Col(pos=4)
    nx_20 = Float64Col(pos=5)
    nx_22 = Float64Col(pos=6)
    nx_23 = Float64Col(pos=7)
    nx_43 = Float64Col(pos=8)
    nx_65 = Float64Col(pos=9)
    nx_66 = Float64Col(pos=10)
    nx_anzahl = IntCol(pos=11)
    Datum = StringCol(10,pos=12)

class HDF5_flaechen_spalten_verteilungen_einordnung_koerper_flaechenbasiert(IsDescription):
    ID = IntCol(pos=0)
    ## einordnung 
    Grundflaechen = Float64Col(pos=1)
    Uebergangsflaechen = Float64Col(pos=2)
    Featureflaechen_konkav = Float64Col(pos=3)
    Featureflaechen_konvex = Float64Col(pos=4)
    Gesamtflaeche=Float64Col(pos=5)
    Datum = StringCol(10,pos=6)
class HDF5_flaechen_spalten_verteilungen_nx_typ_koerper_flaechenbasiert(IsDescription):
    ID = IntCol(pos=0)
    ## NX Typ
    nx_16 = Float64Col(pos=1)
    nx_17 = Float64Col(pos=2)
    nx_18 = Float64Col(pos=3)
    nx_19 = Float64Col(pos=4)
    nx_20 = Float64Col(pos=5)
    nx_22 = Float64Col(pos=6)
    nx_23 = Float64Col(pos=7)
    nx_43 = Float64Col(pos=8)
    nx_65 = Float64Col(pos=9)
    nx_66 = Float64Col(pos=10)
    Gesamtflaeche = Float64Col(pos=11)
    Datum = StringCol(10,pos=12)

class HDF5_flaechen_spalten_kruemmung_flaechen(IsDescription):
    Tag = IntCol(pos=0)
    k_n_25=Float64Col(pos=1)
    k_n_15 = Float64Col(pos=2)
    k_n_10 = Float64Col(pos=3)
    k_n_05 = Float64Col(pos=4)
    k_00 = Float64Col(pos=5)
    k_p_05 = Float64Col(pos=6)
    k_p_10 = Float64Col(pos=7)
    k_p_15 = Float64Col(pos=8)
    k_20 = Float64Col(pos=9)
    k_p_25 = Float64Col(pos=10)
    Anzahl=IntCol(pos=11)
    Datum = StringCol(10,pos=12)

class HDF5_spalten_kruemmung_punkte(IsDescription):
    Tag = StringCol(20,pos=0)
    Gausskruemmung = Float64Col(pos=1)
    Mittlere_Kruemmung = Float64Col(pos=2)
    Kategorie = StringCol(10,pos=3)
    Kruemmungsradius_1 = Float64Col(pos=4)
    Kruemmungsradius_2 = Float64Col(pos=5)
    x = Float64Col(pos=6)
    y = Float64Col(pos=7)
    z = Float64Col(pos=8)
    u = Float64Col(pos=9)
    v = Float64Col(pos=10)
    x_f = Float64Col(pos=11)
    y_f = Float64Col(pos=12)
    z_f = Float64Col(pos=13)
    normx_f=Float64Col(pos=14)
    normy_f=Float64Col(pos=15)
    normz_f=Float64Col(pos=16)
    Datum = StringCol(10,pos=17)